version: 0.2

phases:
  install:
    commands:
      - npm i npm@latest -g
      - node -v
      - pip install --upgrade pip
      - pip install --upgrade awscli
    pre_build:
      commands:
        - echo Pre_build Phase
        - npm install --legacy-peer-deps
    build:
      commands:
        - echo Build Phase
        - npm run build
    post_build:
      commands:
        - echo PostBuild Phase
        - aws s3 sync ./dist s3://sable-frontend-bucket

artifacts:
  files:
    - '**/*'
  base-directory: 'dist' # 여기서 build 폴더를 base-directory로 지정합니다.