version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Pre_build Phase
      - npm install --legacy-peer-deps
  build:
    commands:
      - echo Build Phase
      - npm run build
  post_build:
    commands:
      - echo PostBuild Phase
      - aws s3 sync build/ s3://sable-frontend-bucket
