version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - n 18.17
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  name: "nextjs-build"
  base-directory: build

cache:
  paths:
    - /root/.npm/**/*