version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  pre_build:
    commands:
      - echo Pre_build Phase
      - npm install --legacy-peer-deps
  build:
    commands:
      - echo Build Phase
      - echo "Modifying next.config.mjs for export..."
      - sed -i 's/\/\* Your existing module.exports \*\//module.exports = { output: "export", \/\/ Rest of your config... /' next.config.mjs
      - npm run build
  post_build:
    commands:
      - echo PostBuild Phase
      - aws s3 sync ./build s3://sable-frontend-bucket
